In [4]:
!pip install catboost
!pip install xgboost

Requirement already satisfied: catboost in c:\users\mahadev athani\anaconda3\lib\site-packages (1.2.10)
Requirement already satisfied: graphviz in c:\users\mahadev athani\anaconda3\lib\site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in c:\users\mahadev athani\anaconda3\lib\site-packages (from catboost) (3.9.2)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\mahadev athani\anaconda3\lib\site-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\mahadev athani\anaconda3\lib\site-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in c:\users\mahadev athani\anaconda3\lib\site-packages (from catboost) (1.16.2)
Requirement already satisfied: plotly in c:\users\mahadev athani\anaconda3\lib\site-packages (from catboost) (5.24.1)
Requirement already satisfied: six in c:\users\mahadev athani\anaconda3\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mahadev athani\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mahadev athani\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mahadev athani\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\mahadev athani\anaconda3\lib\site-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\mahadev athani\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\mahadev athani\anaconda3\lib\site-packages (from matplotlib->catboost) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\mahadev athani\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\mahadev athani\anaconda3\lib\site-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\mahadev athani\anaconda3\lib\site-packages (from matplotlib->catboost) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\mahadev athani\anaconda3\lib\site-packages (from matplotlib->catboost) (3.1.2)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\mahadev athani\anaconda3\lib\site-packages (from plotly->catboost) (8.5.0)

WARNING: Ignoring invalid distribution ~cipy (C:\Users\Mahadev Athani\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~cipy (C:\Users\Mahadev Athani\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~cipy (C:\Users\Mahadev Athani\anaconda3\Lib\site-packages)

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\mahadev athani\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\mahadev athani\anaconda3\lib\site-packages (from xgboost) (1.16.2)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 2.1 MB/s eta 0:00:49
   ---------------------------------------- 1.0/101.7 MB 2.2 MB/s eta 0:00:46
    --------------------------------------- 1.8/101.7 MB 2.5 MB/s eta 0:00:40
   - -------------------------------------- 2.9/101.7 MB 3.1 MB/s eta 0:00:33
   - -------------------------------------- 4.2/101.7 MB 3.5 MB/s eta 0:00:28
   -- ------------------------------------- 5.2/101.7 MB 3.9 MB/s eta 0:00:25
   -- ------------------------------------- 6.8/101.7 MB 4.4 MB/s eta 0:00:22
   --- ------------------------------------ 8.7/101.7 MB 4.9 MB/s eta 0:00:20
   ---- ----------------------------------- 10.5/101.7 MB 5.2 MB/s eta 0:00:18
   ---- ----------------------------------- 12.6/101.7 MB 5.8 MB/s eta 0:00:16
   ----- ---------------------------------- 14.7/101.7 MB 6.1 MB/s eta 0:00:15
   ------ --------------------------------- 16.5/101.7 MB 6.4 MB/s eta 0:00:14
   ------- -------------------------------- 18.6/101.7 MB 6.6 MB/s eta 0:00:13
   -------- ------------------------------- 20.7/101.7 MB 6.7 MB/s eta 0:00:13
   --------- ------------------------------ 23.3/101.7 MB 7.1 MB/s eta 0:00:11
   ---------- ----------------------------- 25.4/101.7 MB 7.3 MB/s eta 0:00:11
   ---------- ----------------------------- 27.5/101.7 MB 7.4 MB/s eta 0:00:10
   ----------- ---------------------------- 29.6/101.7 MB 7.6 MB/s eta 0:00:10
   ------------ --------------------------- 32.5/101.7 MB 7.9 MB/s eta 0:00:09
   ------------- -------------------------- 34.6/101.7 MB 8.0 MB/s eta 0:00:09
   -------------- ------------------------- 37.2/101.7 MB 8.2 MB/s eta 0:00:08
   --------------- ------------------------ 38.5/101.7 MB 8.1 MB/s eta 0:00:08
   ---------------- ----------------------- 41.4/101.7 MB 8.4 MB/s eta 0:00:08
   ----------------- ---------------------- 43.5/101.7 MB 8.4 MB/s eta 0:00:07
   ------------------ --------------------- 46.4/101.7 MB 8.7 MB/s eta 0:00:07
   ------------------- -------------------- 48.5/101.7 MB 8.7 MB/s eta 0:00:07
   -------------------- ------------------- 51.1/101.7 MB 8.8 MB/s eta 0:00:06
   --------------------- ------------------ 53.5/101.7 MB 8.9 MB/s eta 0:00:06
   ---------------------- ----------------- 56.1/101.7 MB 9.0 MB/s eta 0:00:06
   ---------------------- ----------------- 58.2/101.7 MB 9.1 MB/s eta 0:00:05
   ----------------------- ---------------- 60.8/101.7 MB 9.2 MB/s eta 0:00:05
   ------------------------ --------------- 63.2/101.7 MB 9.2 MB/s eta 0:00:05
   ------------------------- -------------- 65.8/101.7 MB 9.3 MB/s eta 0:00:04
   -------------------------- ------------- 67.9/101.7 MB 9.3 MB/s eta 0:00:04
   --------------------------- ------------ 70.5/101.7 MB 9.4 MB/s eta 0:00:04
   ---------------------------- ----------- 72.9/101.7 MB 9.5 MB/s eta 0:00:04
   ----------------------------- ---------- 75.5/101.7 MB 9.6 MB/s eta 0:00:03
   ------------------------------ --------- 77.6/101.7 MB 9.6 MB/s eta 0:00:03
   ------------------------------- -------- 80.5/101.7 MB 9.7 MB/s eta 0:00:03
   -------------------------------- ------- 82.3/101.7 MB 9.7 MB/s eta 0:00:02
   --------------------------------- ------ 84.7/101.7 MB 9.7 MB/s eta 0:00:02
   --------------------------------- ------ 86.2/101.7 MB 9.7 MB/s eta 0:00:02
   ---------------------------------- ----- 87.8/101.7 MB 9.6 MB/s eta 0:00:02
   ----------------------------------- ---- 89.9/101.7 MB 9.6 MB/s eta 0:00:02
   ------------------------------------ --- 92.0/101.7 MB 9.6 MB/s eta 0:00:02
   ------------------------------------- -- 94.1/101.7 MB 9.6 MB/s eta 0:00:01
   ------------------------------------- -- 95.9/101.7 MB 9.6 MB/s eta 0:00:01
   -------------------------------------- - 97.8/101.7 MB 9.6 MB/s eta 0:00:01
   ---------------------------------------  99.6/101.7 MB 9.6 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 9.6 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 9.4 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

WARNING: Ignoring invalid distribution ~cipy (C:\Users\Mahadev Athani\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~cipy (C:\Users\Mahadev Athani\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~cipy (C:\Users\Mahadev Athani\anaconda3\Lib\site-packages)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings
from sklearn.model_selection import train_test_split

In [6]:
df=pd.read_csv('data/Stud.csv')

In [7]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [8]:
X=df.drop(columns=['math score'],axis=1)

In [9]:
y=df['math score']

In [10]:
X.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [11]:
num_features=X.select_dtypes(exclude="object").columns
cat_features=X.select_dtypes(include="object").columns

In [12]:
num_features

Index(['reading score', 'writing score'], dtype='object')

In [13]:
cat_features

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course'],
      dtype='object')

In [14]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [15]:
numric_transformer=StandardScaler()
oh_transformer=OneHotEncoder()

preprocessor=ColumnTransformer(
    [
        ("OneHotEncoder",oh_transformer,cat_features),
        ("StandardScaler",numric_transformer,num_features)
    ]
)

In [16]:
X=preprocessor.fit_transform(X)

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [19]:
X_test.shape

(200, 19)

In [20]:
X_train.shape

(800, 19)

In [21]:
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true, predicted)
    rmse=np.sqrt(mean_squared_error(true,predicted))
    r2_square=r2_score(true,predicted)
    return mae,rmse,r2_square

In [24]:
models={
    "Linear Regression":LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
    "K-Neighbors Regressor":KNeighborsRegressor(),
    "Decision Tree":DecisionTreeRegressor(),
    "Random Forest Regressor":RandomForestRegressor(),
    "XGBRegressor":XGBRegressor(),
    "CatBoosting Regressor":CatBoostRegressor(),
    "AdaBoost Regressor":AdaBoostRegressor()
    
}
model_list=[]
r2_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    
    model_train_mae,model_train_rmse, model_train_r2=evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_rmse,model_test_r2=evaluate_model(y_test,y_test_pred)
    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

Linear Regression
Lasso
Ridge
K-Neighbors Regressor
Decision Tree
Random Forest Regressor
XGBRegressor
Learning rate set to 0.039525
0:	learn: 14.5987177	total: 2.11ms	remaining: 2.11s
1:	learn: 14.2251886	total: 6.93ms	remaining: 3.46s
2:	learn: 13.8866124	total: 8.9ms	remaining: 2.96s
3:	learn: 13.5235688	total: 10.8ms	remaining: 2.7s
4:	learn: 13.1887021	total: 14ms	remaining: 2.78s
5:	learn: 12.9124226	total: 15.6ms	remaining: 2.59s
6:	learn: 12.6000335	total: 17.4ms	remaining: 2.46s
7:	learn: 12.3299057	total: 19.9ms	remaining: 2.47s
8:	learn: 12.0660619	total: 22.1ms	remaining: 2.44s
9:	learn: 11.7730981	total: 23.6ms	remaining: 2.34s
10:	learn: 11.4922764	total: 25.6ms	remaining: 2.3s
11:	learn: 11.2626483	total: 29.4ms	remaining: 2.42s
12:	learn: 11.0426039	total: 31.3ms	remaining: 2.38s
13:	learn: 10.7991693	total: 33.2ms	remaining: 2.33s
14:	learn: 10.5541002	total: 35.8ms	remaining: 2.35s
15:	learn: 10.3191811	total: 38.1ms	remaining: 2.34s
16:	learn: 10.1000444	total: 40ms	remaining: 2.31s
17:	learn: 9.8945567	total: 42.5ms	remaining: 2.32s
18:	learn: 9.6901741	total: 44.9ms	remaining: 2.32s
19:	learn: 9.5060349	total: 46.5ms	remaining: 2.28s
20:	learn: 9.3385246	total: 48.9ms	remaining: 2.28s
21:	learn: 9.1702033	total: 51ms	remaining: 2.27s
22:	learn: 9.0103000	total: 53ms	remaining: 2.25s
23:	learn: 8.8438667	total: 55.7ms	remaining: 2.27s
24:	learn: 8.6905481	total: 58.1ms	remaining: 2.26s
25:	learn: 8.5553077	total: 59.6ms	remaining: 2.23s
26:	learn: 8.4138513	total: 61.5ms	remaining: 2.22s
27:	learn: 8.2925602	total: 65.1ms	remaining: 2.26s
28:	learn: 8.1621938	total: 67.3ms	remaining: 2.25s
29:	learn: 8.0407363	total: 69.9ms	remaining: 2.26s
30:	learn: 7.9212203	total: 72ms	remaining: 2.25s
31:	learn: 7.8095890	total: 73.8ms	remaining: 2.23s
32:	learn: 7.6996758	total: 76.2ms	remaining: 2.23s
33:	learn: 7.6064527	total: 78.5ms	remaining: 2.23s
34:	learn: 7.4988803	total: 80.2ms	remaining: 2.21s
35:	learn: 7.4011587	total: 81.9ms	remaining: 2.19s
36:	learn: 7.3064311	total: 84.8ms	remaining: 2.21s
37:	learn: 7.2238635	total: 87.2ms	remaining: 2.21s
38:	learn: 7.1434777	total: 89.5ms	remaining: 2.21s
39:	learn: 7.0628171	total: 92.3ms	remaining: 2.21s
40:	learn: 6.9907934	total: 95.2ms	remaining: 2.23s
41:	learn: 6.9318622	total: 97.2ms	remaining: 2.22s
42:	learn: 6.8582966	total: 99.9ms	remaining: 2.22s
43:	learn: 6.7862682	total: 102ms	remaining: 2.21s
44:	learn: 6.7171185	total: 103ms	remaining: 2.19s
45:	learn: 6.6529481	total: 105ms	remaining: 2.17s
46:	learn: 6.5896861	total: 107ms	remaining: 2.17s
47:	learn: 6.5312831	total: 109ms	remaining: 2.15s
48:	learn: 6.4713680	total: 110ms	remaining: 2.13s
49:	learn: 6.4164814	total: 112ms	remaining: 2.12s
50:	learn: 6.3698708	total: 114ms	remaining: 2.13s
51:	learn: 6.3256781	total: 116ms	remaining: 2.11s
52:	learn: 6.2757661	total: 118ms	remaining: 2.11s
53:	learn: 6.2247740	total: 122ms	remaining: 2.14s
54:	learn: 6.1822493	total: 125ms	remaining: 2.14s
55:	learn: 6.1399042	total: 127ms	remaining: 2.15s
56:	learn: 6.1005255	total: 130ms	remaining: 2.15s
57:	learn: 6.0625686	total: 132ms	remaining: 2.14s
58:	learn: 6.0305593	total: 134ms	remaining: 2.13s
59:	learn: 5.9979314	total: 136ms	remaining: 2.14s
60:	learn: 5.9641038	total: 138ms	remaining: 2.13s
61:	learn: 5.9337297	total: 140ms	remaining: 2.12s
62:	learn: 5.9019327	total: 144ms	remaining: 2.14s
63:	learn: 5.8737278	total: 152ms	remaining: 2.23s
64:	learn: 5.8464857	total: 155ms	remaining: 2.24s
65:	learn: 5.8206309	total: 158ms	remaining: 2.23s
66:	learn: 5.7936462	total: 160ms	remaining: 2.23s
67:	learn: 5.7653886	total: 162ms	remaining: 2.22s
68:	learn: 5.7470739	total: 165ms	remaining: 2.22s
69:	learn: 5.7223152	total: 167ms	remaining: 2.22s
70:	learn: 5.6999706	total: 169ms	remaining: 2.21s
71:	learn: 5.6827326	total: 172ms	remaining: 2.21s
72:	learn: 5.6635258	total: 174ms	remaining: 2.21s
73:	learn: 5.6423816	total: 176ms	remaining: 2.21s
74:	learn: 5.6214048	total: 180ms	remaining: 2.22s
75:	learn: 5.6024601	total: 183ms	remaining: 2.22s
76:	learn: 5.5873376	total: 186ms	remaining: 2.23s
77:	learn: 5.5723930	total: 191ms	remaining: 2.26s
78:	learn: 5.5584258	total: 194ms	remaining: 2.26s
79:	learn: 5.5415189	total: 196ms	remaining: 2.25s
80:	learn: 5.5261573	total: 202ms	remaining: 2.3s
81:	learn: 5.5117470	total: 207ms	remaining: 2.32s
82:	learn: 5.5049750	total: 208ms	remaining: 2.3s
83:	learn: 5.4939805	total: 211ms	remaining: 2.3s
84:	learn: 5.4807455	total: 213ms	remaining: 2.29s
85:	learn: 5.4640520	total: 217ms	remaining: 2.31s
86:	learn: 5.4491437	total: 222ms	remaining: 2.33s
87:	learn: 5.4382554	total: 226ms	remaining: 2.34s
88:	learn: 5.4259279	total: 229ms	remaining: 2.34s
89:	learn: 5.4123312	total: 231ms	remaining: 2.34s
90:	learn: 5.4006915	total: 245ms	remaining: 2.45s
91:	learn: 5.3916187	total: 251ms	remaining: 2.48s
92:	learn: 5.3807666	total: 255ms	remaining: 2.49s
93:	learn: 5.3722072	total: 267ms	remaining: 2.57s
94:	learn: 5.3629188	total: 278ms	remaining: 2.65s
95:	learn: 5.3482923	total: 285ms	remaining: 2.68s
96:	learn: 5.3397723	total: 297ms	remaining: 2.76s
97:	learn: 5.3315160	total: 304ms	remaining: 2.79s
98:	learn: 5.3238616	total: 307ms	remaining: 2.79s
99:	learn: 5.3132773	total: 311ms	remaining: 2.8s
100:	learn: 5.3068563	total: 313ms	remaining: 2.79s
101:	learn: 5.2965206	total: 317ms	remaining: 2.79s
102:	learn: 5.2883508	total: 320ms	remaining: 2.79s
103:	learn: 5.2799335	total: 325ms	remaining: 2.79s
104:	learn: 5.2717891	total: 327ms	remaining: 2.78s
105:	learn: 5.2626847	total: 334ms	remaining: 2.82s
106:	learn: 5.2516198	total: 344ms	remaining: 2.87s
107:	learn: 5.2410122	total: 357ms	remaining: 2.94s
108:	learn: 5.2326840	total: 364ms	remaining: 2.97s
109:	learn: 5.2242671	total: 367ms	remaining: 2.96s
110:	learn: 5.2163250	total: 369ms	remaining: 2.95s
111:	learn: 5.2111025	total: 372ms	remaining: 2.95s
112:	learn: 5.2063643	total: 376ms	remaining: 2.95s
113:	learn: 5.1969376	total: 379ms	remaining: 2.94s
114:	learn: 5.1907460	total: 384ms	remaining: 2.96s
115:	learn: 5.1818852	total: 387ms	remaining: 2.95s
116:	learn: 5.1782936	total: 389ms	remaining: 2.94s
117:	learn: 5.1709914	total: 416ms	remaining: 3.11s
118:	learn: 5.1662572	total: 422ms	remaining: 3.12s
119:	learn: 5.1614212	total: 424ms	remaining: 3.11s
120:	learn: 5.1582235	total: 428ms	remaining: 3.11s
121:	learn: 5.1547099	total: 430ms	remaining: 3.1s
122:	learn: 5.1463881	total: 433ms	remaining: 3.08s
123:	learn: 5.1395294	total: 437ms	remaining: 3.09s
124:	learn: 5.1342760	total: 443ms	remaining: 3.1s
125:	learn: 5.1285361	total: 446ms	remaining: 3.09s
126:	learn: 5.1233004	total: 451ms	remaining: 3.1s
127:	learn: 5.1162005	total: 459ms	remaining: 3.13s
128:	learn: 5.1087287	total: 467ms	remaining: 3.15s
129:	learn: 5.1040759	total: 477ms	remaining: 3.19s
130:	learn: 5.1003176	total: 494ms	remaining: 3.28s
131:	learn: 5.0958142	total: 498ms	remaining: 3.27s
132:	learn: 5.0921469	total: 501ms	remaining: 3.26s
133:	learn: 5.0852583	total: 504ms	remaining: 3.26s
134:	learn: 5.0792194	total: 507ms	remaining: 3.25s
135:	learn: 5.0764768	total: 514ms	remaining: 3.27s
136:	learn: 5.0721339	total: 517ms	remaining: 3.26s
137:	learn: 5.0670316	total: 522ms	remaining: 3.26s
138:	learn: 5.0613583	total: 531ms	remaining: 3.29s
139:	learn: 5.0567591	total: 544ms	remaining: 3.34s
140:	learn: 5.0502540	total: 548ms	remaining: 3.34s
141:	learn: 5.0483765	total: 550ms	remaining: 3.32s
142:	learn: 5.0426038	total: 552ms	remaining: 3.31s
143:	learn: 5.0374773	total: 556ms	remaining: 3.31s
144:	learn: 5.0323049	total: 560ms	remaining: 3.3s
145:	learn: 5.0259762	total: 563ms	remaining: 3.29s
146:	learn: 5.0195245	total: 567ms	remaining: 3.29s
147:	learn: 5.0175694	total: 570ms	remaining: 3.28s
148:	learn: 5.0089624	total: 574ms	remaining: 3.28s
149:	learn: 5.0038803	total: 578ms	remaining: 3.27s
150:	learn: 4.9963876	total: 581ms	remaining: 3.27s
151:	learn: 4.9933617	total: 587ms	remaining: 3.27s
152:	learn: 4.9900575	total: 589ms	remaining: 3.26s
153:	learn: 4.9869088	total: 594ms	remaining: 3.26s
154:	learn: 4.9852072	total: 597ms	remaining: 3.25s
155:	learn: 4.9790035	total: 602ms	remaining: 3.25s
156:	learn: 4.9731422	total: 607ms	remaining: 3.26s
157:	learn: 4.9670567	total: 609ms	remaining: 3.25s
158:	learn: 4.9614607	total: 614ms	remaining: 3.25s
159:	learn: 4.9542404	total: 619ms	remaining: 3.25s
160:	learn: 4.9523207	total: 622ms	remaining: 3.24s
161:	learn: 4.9483378	total: 626ms	remaining: 3.24s
162:	learn: 4.9432286	total: 633ms	remaining: 3.25s
163:	learn: 4.9385458	total: 637ms	remaining: 3.25s
164:	learn: 4.9353306	total: 639ms	remaining: 3.23s
165:	learn: 4.9320515	total: 641ms	remaining: 3.22s
166:	learn: 4.9289642	total: 645ms	remaining: 3.22s
167:	learn: 4.9228602	total: 650ms	remaining: 3.22s
168:	learn: 4.9176688	total: 654ms	remaining: 3.21s
169:	learn: 4.9103654	total: 656ms	remaining: 3.21s
170:	learn: 4.9064572	total: 660ms	remaining: 3.2s
171:	learn: 4.9019965	total: 663ms	remaining: 3.19s
172:	learn: 4.8968162	total: 668ms	remaining: 3.19s
173:	learn: 4.8911231	total: 670ms	remaining: 3.18s
174:	learn: 4.8876302	total: 673ms	remaining: 3.17s
175:	learn: 4.8852597	total: 676ms	remaining: 3.17s
176:	learn: 4.8806597	total: 679ms	remaining: 3.15s
177:	learn: 4.8772997	total: 682ms	remaining: 3.15s
178:	learn: 4.8740388	total: 684ms	remaining: 3.14s
179:	learn: 4.8694370	total: 689ms	remaining: 3.14s
180:	learn: 4.8612687	total: 693ms	remaining: 3.14s
181:	learn: 4.8586731	total: 701ms	remaining: 3.15s
182:	learn: 4.8540362	total: 703ms	remaining: 3.14s
183:	learn: 4.8513024	total: 712ms	remaining: 3.16s
184:	learn: 4.8475101	total: 715ms	remaining: 3.15s
185:	learn: 4.8456917	total: 718ms	remaining: 3.14s
186:	learn: 4.8420586	total: 735ms	remaining: 3.19s
187:	learn: 4.8386237	total: 742ms	remaining: 3.2s
188:	learn: 4.8346022	total: 744ms	remaining: 3.19s
189:	learn: 4.8308590	total: 751ms	remaining: 3.2s
190:	learn: 4.8275905	total: 755ms	remaining: 3.2s
191:	learn: 4.8222462	total: 758ms	remaining: 3.19s
192:	learn: 4.8166864	total: 765ms	remaining: 3.2s
193:	learn: 4.8147971	total: 771ms	remaining: 3.2s
194:	learn: 4.8116394	total: 775ms	remaining: 3.2s
195:	learn: 4.8048134	total: 777ms	remaining: 3.19s
196:	learn: 4.8025161	total: 779ms	remaining: 3.18s
197:	learn: 4.8000879	total: 784ms	remaining: 3.17s
198:	learn: 4.7947731	total: 786ms	remaining: 3.16s
199:	learn: 4.7916648	total: 788ms	remaining: 3.15s
200:	learn: 4.7859899	total: 792ms	remaining: 3.15s
201:	learn: 4.7823871	total: 793ms	remaining: 3.13s
202:	learn: 4.7786237	total: 795ms	remaining: 3.12s
203:	learn: 4.7757722	total: 798ms	remaining: 3.11s
204:	learn: 4.7702310	total: 800ms	remaining: 3.1s
205:	learn: 4.7644967	total: 802ms	remaining: 3.09s
206:	learn: 4.7631387	total: 806ms	remaining: 3.09s
207:	learn: 4.7580533	total: 808ms	remaining: 3.08s
208:	learn: 4.7550638	total: 812ms	remaining: 3.07s
209:	learn: 4.7524653	total: 815ms	remaining: 3.07s
210:	learn: 4.7480674	total: 818ms	remaining: 3.06s
211:	learn: 4.7441633	total: 822ms	remaining: 3.05s
212:	learn: 4.7366709	total: 824ms	remaining: 3.04s
213:	learn: 4.7334926	total: 827ms	remaining: 3.04s
214:	learn: 4.7318646	total: 829ms	remaining: 3.03s
215:	learn: 4.7283983	total: 832ms	remaining: 3.02s
216:	learn: 4.7238660	total: 835ms	remaining: 3.01s
217:	learn: 4.7234834	total: 837ms	remaining: 3s
218:	learn: 4.7209542	total: 846ms	remaining: 3.02s
219:	learn: 4.7161734	total: 849ms	remaining: 3.01s
220:	learn: 4.7105640	total: 851ms	remaining: 3s
221:	learn: 4.7071603	total: 855ms	remaining: 2.99s
222:	learn: 4.7040835	total: 857ms	remaining: 2.99s
223:	learn: 4.7025018	total: 859ms	remaining: 2.98s
224:	learn: 4.7002697	total: 863ms	remaining: 2.97s
225:	learn: 4.6953463	total: 866ms	remaining: 2.96s
226:	learn: 4.6897693	total: 869ms	remaining: 2.96s
227:	learn: 4.6879195	total: 872ms	remaining: 2.95s
228:	learn: 4.6829821	total: 876ms	remaining: 2.95s
229:	learn: 4.6795787	total: 883ms	remaining: 2.96s
230:	learn: 4.6757514	total: 885ms	remaining: 2.95s
231:	learn: 4.6727107	total: 888ms	remaining: 2.94s
232:	learn: 4.6690533	total: 892ms	remaining: 2.94s
233:	learn: 4.6675957	total: 898ms	remaining: 2.94s
234:	learn: 4.6642413	total: 901ms	remaining: 2.93s
235:	learn: 4.6622470	total: 903ms	remaining: 2.92s
236:	learn: 4.6586684	total: 907ms	remaining: 2.92s
237:	learn: 4.6580176	total: 909ms	remaining: 2.91s
238:	learn: 4.6576567	total: 912ms	remaining: 2.9s
239:	learn: 4.6532429	total: 914ms	remaining: 2.89s
240:	learn: 4.6507302	total: 918ms	remaining: 2.89s
241:	learn: 4.6476713	total: 923ms	remaining: 2.89s
242:	learn: 4.6455060	total: 926ms	remaining: 2.88s
243:	learn: 4.6412979	total: 929ms	remaining: 2.88s
244:	learn: 4.6379811	total: 931ms	remaining: 2.87s
245:	learn: 4.6350623	total: 933ms	remaining: 2.86s
246:	learn: 4.6316060	total: 936ms	remaining: 2.85s
247:	learn: 4.6302155	total: 938ms	remaining: 2.84s
248:	learn: 4.6272981	total: 941ms	remaining: 2.84s
249:	learn: 4.6246918	total: 943ms	remaining: 2.83s
250:	learn: 4.6218401	total: 946ms	remaining: 2.82s
251:	learn: 4.6196021	total: 949ms	remaining: 2.82s
252:	learn: 4.6135840	total: 953ms	remaining: 2.81s
253:	learn: 4.6119388	total: 958ms	remaining: 2.81s
254:	learn: 4.6087070	total: 960ms	remaining: 2.81s
255:	learn: 4.6047716	total: 964ms	remaining: 2.8s
256:	learn: 4.6042313	total: 967ms	remaining: 2.79s
257:	learn: 4.6007504	total: 969ms	remaining: 2.79s
258:	learn: 4.5964883	total: 972ms	remaining: 2.78s
259:	learn: 4.5947078	total: 974ms	remaining: 2.77s
260:	learn: 4.5888180	total: 977ms	remaining: 2.77s
261:	learn: 4.5850542	total: 980ms	remaining: 2.76s
262:	learn: 4.5814714	total: 983ms	remaining: 2.75s
263:	learn: 4.5775552	total: 995ms	remaining: 2.77s
264:	learn: 4.5745714	total: 998ms	remaining: 2.77s
265:	learn: 4.5730292	total: 1s	remaining: 2.76s
266:	learn: 4.5713262	total: 1s	remaining: 2.76s
267:	learn: 4.5710192	total: 1.01s	remaining: 2.75s
268:	learn: 4.5657666	total: 1.01s	remaining: 2.74s
269:	learn: 4.5633835	total: 1.01s	remaining: 2.73s
270:	learn: 4.5581658	total: 1.02s	remaining: 2.73s
271:	learn: 4.5562921	total: 1.02s	remaining: 2.73s
272:	learn: 4.5493838	total: 1.02s	remaining: 2.72s
273:	learn: 4.5462275	total: 1.02s	remaining: 2.71s
274:	learn: 4.5406210	total: 1.02s	remaining: 2.7s
275:	learn: 4.5328982	total: 1.03s	remaining: 2.69s
276:	learn: 4.5297574	total: 1.03s	remaining: 2.69s
277:	learn: 4.5257929	total: 1.03s	remaining: 2.68s
278:	learn: 4.5215722	total: 1.03s	remaining: 2.67s
279:	learn: 4.5188181	total: 1.04s	remaining: 2.67s
280:	learn: 4.5140123	total: 1.04s	remaining: 2.66s
281:	learn: 4.5083314	total: 1.04s	remaining: 2.65s
282:	learn: 4.5060385	total: 1.04s	remaining: 2.65s
283:	learn: 4.5058056	total: 1.05s	remaining: 2.64s
284:	learn: 4.5015504	total: 1.05s	remaining: 2.63s
285:	learn: 4.4946926	total: 1.05s	remaining: 2.62s
286:	learn: 4.4893302	total: 1.05s	remaining: 2.62s
287:	learn: 4.4848270	total: 1.05s	remaining: 2.61s
288:	learn: 4.4782854	total: 1.06s	remaining: 2.61s
289:	learn: 4.4753117	total: 1.06s	remaining: 2.6s
290:	learn: 4.4715813	total: 1.07s	remaining: 2.6s
291:	learn: 4.4691650	total: 1.07s	remaining: 2.59s
292:	learn: 4.4620680	total: 1.07s	remaining: 2.58s
293:	learn: 4.4585410	total: 1.08s	remaining: 2.58s
294:	learn: 4.4557575	total: 1.08s	remaining: 2.58s
295:	learn: 4.4530274	total: 1.08s	remaining: 2.57s
296:	learn: 4.4506593	total: 1.08s	remaining: 2.56s
297:	learn: 4.4446969	total: 1.09s	remaining: 2.56s
298:	learn: 4.4420528	total: 1.09s	remaining: 2.56s
299:	learn: 4.4400368	total: 1.09s	remaining: 2.55s
300:	learn: 4.4350171	total: 1.09s	remaining: 2.54s
301:	learn: 4.4299621	total: 1.1s	remaining: 2.54s
302:	learn: 4.4276663	total: 1.1s	remaining: 2.53s
303:	learn: 4.4250300	total: 1.1s	remaining: 2.53s
304:	learn: 4.4225888	total: 1.1s	remaining: 2.52s
305:	learn: 4.4189367	total: 1.11s	remaining: 2.51s
306:	learn: 4.4168880	total: 1.11s	remaining: 2.51s
307:	learn: 4.4137734	total: 1.11s	remaining: 2.5s
308:	learn: 4.4111294	total: 1.12s	remaining: 2.5s
309:	learn: 4.4085082	total: 1.12s	remaining: 2.49s
310:	learn: 4.4048803	total: 1.12s	remaining: 2.49s
311:	learn: 4.4045938	total: 1.12s	remaining: 2.48s
312:	learn: 4.4021399	total: 1.13s	remaining: 2.47s
313:	learn: 4.4002847	total: 1.13s	remaining: 2.47s
314:	learn: 4.3958055	total: 1.13s	remaining: 2.46s
315:	learn: 4.3928388	total: 1.13s	remaining: 2.46s
316:	learn: 4.3892131	total: 1.14s	remaining: 2.45s
317:	learn: 4.3861981	total: 1.14s	remaining: 2.44s
318:	learn: 4.3850542	total: 1.14s	remaining: 2.44s
319:	learn: 4.3793646	total: 1.14s	remaining: 2.43s
320:	learn: 4.3783876	total: 1.15s	remaining: 2.42s
321:	learn: 4.3758167	total: 1.15s	remaining: 2.42s
322:	learn: 4.3746002	total: 1.15s	remaining: 2.41s
323:	learn: 4.3709890	total: 1.16s	remaining: 2.41s
324:	learn: 4.3674185	total: 1.16s	remaining: 2.4s
325:	learn: 4.3635846	total: 1.16s	remaining: 2.4s
326:	learn: 4.3607707	total: 1.16s	remaining: 2.39s
327:	learn: 4.3586758	total: 1.17s	remaining: 2.39s
328:	learn: 4.3542282	total: 1.17s	remaining: 2.39s
329:	learn: 4.3537734	total: 1.18s	remaining: 2.39s
330:	learn: 4.3516480	total: 1.18s	remaining: 2.38s
331:	learn: 4.3482099	total: 1.18s	remaining: 2.38s
332:	learn: 4.3458527	total: 1.19s	remaining: 2.38s
333:	learn: 4.3423734	total: 1.19s	remaining: 2.37s
334:	learn: 4.3408144	total: 1.19s	remaining: 2.37s
335:	learn: 4.3397071	total: 1.2s	remaining: 2.37s
336:	learn: 4.3354308	total: 1.2s	remaining: 2.36s
337:	learn: 4.3352189	total: 1.2s	remaining: 2.36s
338:	learn: 4.3285072	total: 1.21s	remaining: 2.35s
339:	learn: 4.3261407	total: 1.21s	remaining: 2.35s
340:	learn: 4.3237856	total: 1.21s	remaining: 2.35s
341:	learn: 4.3206325	total: 1.22s	remaining: 2.34s
342:	learn: 4.3197372	total: 1.22s	remaining: 2.34s
343:	learn: 4.3180009	total: 1.23s	remaining: 2.34s
344:	learn: 4.3127136	total: 1.23s	remaining: 2.33s
345:	learn: 4.3082208	total: 1.23s	remaining: 2.33s
346:	learn: 4.3058909	total: 1.24s	remaining: 2.33s
347:	learn: 4.3051379	total: 1.25s	remaining: 2.34s
348:	learn: 4.3047872	total: 1.26s	remaining: 2.35s
349:	learn: 4.3035013	total: 1.26s	remaining: 2.34s
350:	learn: 4.3029381	total: 1.26s	remaining: 2.34s
351:	learn: 4.2995485	total: 1.27s	remaining: 2.34s
352:	learn: 4.2947684	total: 1.27s	remaining: 2.33s
353:	learn: 4.2945815	total: 1.28s	remaining: 2.33s
354:	learn: 4.2925516	total: 1.28s	remaining: 2.33s
355:	learn: 4.2886289	total: 1.28s	remaining: 2.32s
356:	learn: 4.2878028	total: 1.29s	remaining: 2.32s
357:	learn: 4.2845669	total: 1.29s	remaining: 2.31s
358:	learn: 4.2789023	total: 1.29s	remaining: 2.31s
359:	learn: 4.2769380	total: 1.3s	remaining: 2.31s
360:	learn: 4.2734251	total: 1.3s	remaining: 2.3s
361:	learn: 4.2697265	total: 1.3s	remaining: 2.3s
362:	learn: 4.2655659	total: 1.31s	remaining: 2.29s
363:	learn: 4.2621172	total: 1.31s	remaining: 2.29s
364:	learn: 4.2591851	total: 1.32s	remaining: 2.3s
365:	learn: 4.2576685	total: 1.32s	remaining: 2.29s
366:	learn: 4.2534324	total: 1.33s	remaining: 2.29s
367:	learn: 4.2502167	total: 1.34s	remaining: 2.3s
368:	learn: 4.2451483	total: 1.34s	remaining: 2.29s
369:	learn: 4.2440158	total: 1.34s	remaining: 2.29s
370:	learn: 4.2403292	total: 1.35s	remaining: 2.28s
371:	learn: 4.2367180	total: 1.35s	remaining: 2.28s
372:	learn: 4.2334959	total: 1.35s	remaining: 2.28s
373:	learn: 4.2303575	total: 1.36s	remaining: 2.27s
374:	learn: 4.2273812	total: 1.36s	remaining: 2.27s
375:	learn: 4.2261691	total: 1.37s	remaining: 2.27s
376:	learn: 4.2259639	total: 1.37s	remaining: 2.27s
377:	learn: 4.2243465	total: 1.38s	remaining: 2.26s
378:	learn: 4.2225954	total: 1.38s	remaining: 2.26s
379:	learn: 4.2197009	total: 1.38s	remaining: 2.26s
380:	learn: 4.2163562	total: 1.39s	remaining: 2.25s
381:	learn: 4.2143265	total: 1.39s	remaining: 2.25s
382:	learn: 4.2129014	total: 1.39s	remaining: 2.24s
383:	learn: 4.2113311	total: 1.4s	remaining: 2.24s